### ISSUE TITLE
Crash when dismissing activity from recent apps

### ISSUE THREAD

**Issue by thornySoap** [Malopieds/InnerTune#127]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Play a song
2. Dismiss it from the recent apps screen

### Expected behavior

Music should continue in background

### Actual behavior

Playback stops

### Logs

```
FATAL EXCEPTION: main
Process: com.zionhuang.music, PID: 20732
java.lang.RuntimeException: Unable to destroy activity {com.zionhuang.music/com.zionhuang.music.MainActivity}: java.lang.IllegalArgumentException: Service not registered: android.support.v4.media.g@21ed674
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5827)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5859)
	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:254)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:228)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:91)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2544)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.IllegalArgumentException: Service not registered: android.support.v4.media.g@21ed674
	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:2009)
	at android.app.ContextImpl.unbindService(ContextImpl.java:2169)
	at android.content.ContextWrapper.unbindService(ContextWrapper.java:924)
	at com.zionhuang.music.MainActivity.onDestroy(SourceFile:41)
	at android.app.Activity.performDestroy(Activity.java:9048)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1554)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5814)
	... 14 more
```

### InnerTune version

0.5.7-rc2

### Android version

Android 14 Lineage OS 21

**Comment by Malopieds** [comment]
Yes I didn't implemented fully this functionality, I wanted to let the user be able to choose between closing it when dismissing and letting it play but it's not ready completely.
