### ISSUE TITLE
Errors in playing music 

### ISSUE THREAD

**Issue by Chuaaaa-rl** [Malopieds/InnerTune#438]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Randomly open the songs you want 
2. Play the song until about 30s
3. Error occurs 

https://github.com/user-attachments/assets/b8333cbd-8526-44f9-99e5-dd31fe61dc3f

### Expected behavior

The song should be play

### Actual behavior

Error occurs in playing music 

### Screenshots/Screen recordings

I have logged out my account and the errors is temporary fixed. However,this bug produced suddenly and all of the songs couldn't be played. I tried this in YouTube Music and Spotify and both were function normally.

### Logs

.

### InnerTune version

0.5.12

### Android version

Android 13

**Comment by zeeshan0022** [comment]
Facing same song playing for 30 to 35s then error unknown

**Comment by Mrunknow3** [comment]
Same

**Comment by ghost** [comment]
Second and third for this.
I personally have had this happen this morning,
and a friend I had set up with it is also seeing this issue.

**Comment by Andek0** [comment]
same problem

**Comment by MissoulaHugin** [comment]
same

**Comment by MissoulaHugin** [comment]
same

![1000003173](https://github.com/user-attachments/assets/3c249b7c-7231-4fa3-abe9-d5b50e0e08ef)

**Comment by pooransuthar** [comment]
Same for me as well.

**Comment by Shadowbee27** [comment]
Same problem with not downloaded music

**Comment by Lorestan00** [comment]
![1734779332853.jpg](https://github.com/user-attachments/assets/cc88e5dd-8819-47a0-94aa-f14f7f9144c5)

Same problem. Anything not downloaded doesn't play and has 'unknown error' appear. Tried to clear cache no difference. On latest version

Hope the developer looks into this soon

**Comment by unsignedchar-256** [comment]
```
2024-12-21 21:22:08.611  8587-8678  ExoPlayerImplInternal   com.malopieds.innertune.debug        E  Playback error
                                                                                                      androidx.media3.exoplayer.ExoPlaybackException: Source error
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:736)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:708)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                          at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                          at android.os.Looper.loop(Looper.java:319)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                      Caused by: androidx.media3.datasource.HttpDataSource$InvalidResponseCodeException: Response code: 403
                                                                                                          at androidx.media3.datasource.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:304)
                                                                                                          at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:275)
                                                                                                          at androidx.media3.datasource.TeeDataSource.open(TeeDataSource.java:54)
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:802)
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:615)
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:802)
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:615)
                                                                                                          at androidx.media3.datasource.ResolvingDataSource.open(ResolvingDataSource.java:110)
                                                                                                          at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
                                                                                                          at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1045)
                                                                                                          at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                          at java.lang.Thread.run(Thread.java:1012)
```

Is it an API change or something?

**Comment by ghost** [comment]
> Is it an API change or something?

Response code 403 means "forbidden"

Google's gotten wise to whatever method InnerTune is using.
I'm sure there were other apps using the same, and a new way in will be found.

Just a matter of time.

**Comment by unsignedchar-256** [comment]
> > Is it an API change or something?
> 
> Response code 403 means "forbidden"
> 
> Google's gotten wise to whatever method InnerTune is using. I'm sure there were other apps using the same, and a new way in will be found.
> 
> Just a matter of time.


Ikr, but last commit was 3 weeks ago feels like...

(OuterTune made a fix but Malopieds need to do the same)

**Comment by ff2400t** [comment]
I had the same Issue. So the fix for now is to Log out of your Account in the InnerTune App. In my case I had ogged in a long time ago so I had to login again and then click sign out in the Webview.  This is based on the Fix that OuterTune implement, they pretend that the user is not signed in when the app is requesting the Songs.

Edit: doesn't work after a while

**Comment by ekeppel** [comment]
+1

I tried reverting to an earlier version 0.5.8 / 0.5.9 to see if it would fix it, but no luck there.  Unfortunately, all of my downloaded music is gone, and I can't re-download any of it until the next patch.  It's too bad that downloaded music doesn't persist in a directory somewhere when the app is uninstalled, but still love this app when it's working. :-)

**Comment by unsignedchar-256** [comment]
> I had the same Issue. So the fix for now is to Log out of your Account in the InnerTune App. In my case I had logged in a long time ago so I had to login again and then click sign out in the Webview. This is based on the Fix that Outer Tune implement, they pretend that the user is not signed in when the app is requesting the Songs.

I used IT without signing in but still got the same issue.

![Screenshot_20241222_092313_InnerTune](https://github.com/user-attachments/assets/a9505104-07c2-461f-bee3-6ce7588d7f01)

**Comment by unsignedchar-256** [comment]
> +1
> 
> I tried reverting to an earlier version 0.5.8 / 0.5.9 to see if it would fix it, but no luck there. Unfortunately, all of my downloaded music is gone, and I can't re-download any of it until the next patch. It's too bad that downloaded music doesn't persist in a directory somewhere when the app is uninstalled, but still love this app when it's working. :-)

Isn't it normal? Most streaming apps do the same thing, saving downloaded music in app data.

(You can use the debug version if you want to make the app data accessible)

**Comment by H4RRY247** [comment]
> > +1
> > 
> > I tried reverting to an earlier version 0.5.8 / 0.5.9 to see if it would fix it, but no luck there. Unfortunately, all of my downloaded music is gone, and I can't re-download any of it until the next patch. It's too bad that downloaded music doesn't persist in a directory somewhere when the app is uninstalled, but still love this app when it's working. :-)
> 
> Isn't it normal? Most streaming apps do the same thing, saving downloaded music in app data.
> 
> (You can use the debug version if you want to make the app data accessible)


Any ideas about getting the debug version??

**Comment by ghost** [comment]
> > +1
> > I tried reverting to an earlier version 0.5.8 / 0.5.9 to see if it would fix it, but no luck there. Unfortunately, all of my downloaded music is gone, and I can't re-download any of it until the next patch. It's too bad that downloaded music doesn't persist in a directory somewhere when the app is uninstalled, but still love this app when it's working. :-)
> 
> Isn't it normal? Most streaming apps do the same thing, saving downloaded music in app data.
> 
> (You can use the debug version if you want to make the app data accessible)

some FOSS streaming apps, or Downloaders will allow you to define an external folder to save to. I think that's what they were referring to.

**Comment by H4RRY247** [comment]
> > > +1
> > > I tried reverting to an earlier version 0.5.8 / 0.5.9 to see if it would fix it, but no luck there. Unfortunately, all of my downloaded music is gone, and I can't re-download any of it until the next patch. It's too bad that downloaded music doesn't persist in a directory somewhere when the app is uninstalled, but still love this app when it's working. :-)
> > 
> > Isn't it normal? Most streaming apps do the same thing, saving downloaded music in app data.
> > 
> > (You can use the debug version if you want to make the app data accessible)
> 
> some FOSS streaming apps, or Downloaders will allow you to define an external folder to save to. I think that's what they were referring to.


I have used outertunes but it lags for me no matter what do you have any idea about getting something in innertunes so that it would save songs locally?

**Comment by user-1-2-3-4-5** [comment]
[Newpipe](https://github.com/TeamNewPipe/NewPipe) works at the time, I played several hours of audio from Youtube Music today.

I'm specifically using [the Tubular fork](https://github.com/polymorphicshade/Tubular) (with Sponsorblock), which  is one release behind the upstream (`0.27.2`).

**Comment by catgangdev** [comment]
> [Newpipe](https://github.com/TeamNewPipe/NewPipe) works at the time, I played several hours of audio from Youtube Music today.

Meanwhile using Ymusic

**Comment by unsignedchar-256** [comment]
> > > +1
> > > I tried reverting to an earlier version 0.5.8 / 0.5.9 to see if it would fix it, but no luck there. Unfortunately, all of my downloaded music is gone, and I can't re-download any of it until the next patch. It's too bad that downloaded music doesn't persist in a directory somewhere when the app is uninstalled, but still love this app when it's working. :-)
> > 
> > 
> > Isn't it normal? Most streaming apps do the same thing, saving downloaded music in app data.
> > (You can use the debug version if you want to make the app data accessible)
> 
> Any ideas about getting the debug version??

You can build this project from your IDE (e.g., Android Studio). But debug APKs are so much laggy and not recommended for daily use. But it allows you to access the app data from Device Manager in Android Studio.

**Comment by unsignedchar-256** [comment]
> +1
> 
> I tried reverting to an earlier version 0.5.8 / 0.5.9 to see if it would fix it, but no luck there. Unfortunately, all of my downloaded music is gone, and I can't re-download any of it until the next patch. It's too bad that downloaded music doesn't persist in a directory somewhere when the app is uninstalled, but still love this app when it's working. :-)

You can use [Seal](https://github.com/JunkFood02/Seal) if you want to download files manually, or use [Cobalt](https://cobalt.tools/) for the web version.

**Comment by ecv80** [comment]
This seems like a duplicate of #433

**Comment by unsignedchar-256** [comment]
> This seems like a duplicate of #433

The issue was opened last week and I didn't experience that last week. I just started to experience this when this issue opened, which is 4 days ago.
