### ISSUE TITLE
Youtube Videos with only mp4 / aac audio fails to play

### ISSUE THREAD

**Issue by ifacify** [Malopieds/InnerTune#68]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Search for `https://youtu.be/9sb-jztmdN8?list=PLJL0SL186iqzQq2o7Ss4pCYyL37JeqSEb` and `https://youtu.be/JQBQXzxiMcg?list=PLJL0SL186iqzQq2o7Ss4pCYyL37JeqSEb` and play them. The first one does not play and throws [ERROR_CODE_NO_STREAM](https://github.com/Malopieds/InnerTune/blob/db3d8f93424d37f7be2d1686505ba4acde21def5/app/src/main/java/com/zionhuang/music/playback/MusicService.kt#L621) while the latter plays just fine.

```
$ yt-dlp -qF --no-playlist https://youtu.be/9sb-jztmdN8?list=PLJL0SL186iqzQq2o7Ss4pCYyL37JeqSEb
ID  EXT   RESOLUTION FPS CH │   FILESIZE  TBR PROTO │ VCODEC         VBR ACODEC      ABR ASR MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2 mhtml 48x27        0    │                 mhtml │ images                                 storyboard
sb1 mhtml 60x45        1    │                 mhtml │ images                                 storyboard
sb0 mhtml 120x90       1    │                 mhtml │ images                                 storyboard
233 mp4   audio only        │                 m3u8  │ audio only         unknown             [en] Default
234 mp4   audio only        │                 m3u8  │ audio only         unknown             [en] Default
139 m4a   audio only      2 │    1.51MiB  49k https │ audio only         mp4a.40.5   49k 22k [en] low, m4a_dash
140 m4a   audio only      2 │    4.01MiB 129k https │ audio only         mp4a.40.2  129k 44k [en] medium, m4a_dash
269 mp4   192x144     30    │ ~  2.22MiB  72k m3u8  │ avc1.4D400C    72k video only
160 mp4   192x144     30    │  467.44KiB  15k https │ avc1.4D400C    15k video only          144p, mp4_dash
230 mp4   480x360     30    │ ~  5.96MiB 192k m3u8  │ avc1.4D401E   192k video only
134 mp4   480x360     30    │    1.25MiB  40k https │ avc1.4D401E    40k video only          360p, mp4_dash
18  mp4   480x360     30  2 │ ≈  5.24MiB 169k https │ avc1.42001E        mp4a.40.2       44k [en] 360p
605 mp4   480x360     30    │ ~  5.53MiB 179k m3u8  │ vp09.00.21.08 179k video only
231 mp4   640x480     30    │ ~  6.80MiB 219k m3u8  │ avc1.4D401E   219k video only
135 mp4   640x480     30    │    1.74MiB  56k https │ avc1.4D401E    56k video only          480p, mp4_dash
```
```
$ yt-dlp -qF --no-playlist https://youtu.be/JQBQXzxiMcg?list=PLJL0SL186iqzQq2o7Ss4pCYyL37JeqSEb
ID  EXT   RESOLUTION FPS CH │   FILESIZE  TBR PROTO │ VCODEC         VBR ACODEC      ABR ASR MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2 mhtml 48x27        1    │                 mhtml │ images                                 storyboard
sb1 mhtml 60x45        1    │                 mhtml │ images                                 storyboard
sb0 mhtml 120x90       1    │                 mhtml │ images                                 storyboard
233 mp4   audio only        │                 m3u8  │ audio only         unknown             Default
234 mp4   audio only        │                 m3u8  │ audio only         unknown             Default
139 m4a   audio only      2 │  878.54KiB  48k https │ audio only         mp4a.40.5   48k 22k low, m4a_dash
249 webm  audio only      2 │    1.12MiB  62k https │ audio only         opus        62k 48k low, webm_dash
250 webm  audio only      2 │    1.39MiB  77k https │ audio only         opus        77k 48k low, webm_dash
140 m4a   audio only      2 │    2.29MiB 127k https │ audio only         mp4a.40.2  127k 44k medium, m4a_dash
251 webm  audio only      2 │    2.68MiB 149k https │ audio only         opus       149k 48k medium, webm_dash
269 mp4   192x144     15    │ ~  2.81MiB 156k m3u8  │ avc1.4D400C   156k video only
160 mp4   192x144     15    │  834.62KiB  45k https │ avc1.4D400C    45k video only          144p, mp4_dash
603 mp4   192x144     30    │ ~  1.71MiB  95k m3u8  │ vp09.00.11.08  95k video only
278 webm  192x144     30    │  305.73KiB  17k https │ vp09.00.11.08  17k video only          144p, webm_dash
229 mp4   320x240     30    │ ~  3.94MiB 219k m3u8  │ avc1.4D400D   219k video only
133 mp4   320x240     30    │    1.01MiB  56k https │ avc1.4D400D    56k video only          240p, mp4_dash
604 mp4   320x240     30    │ ~  2.54MiB 141k m3u8  │ vp09.00.20.08 141k video only
242 webm  320x240     30    │  525.96KiB  29k https │ vp09.00.20.08  29k video only          240p, webm_dash
230 mp4   480x360     30    │ ~  7.28MiB 404k m3u8  │ avc1.4D401E   404k video only
134 mp4   480x360     30    │    1.75MiB  97k https │ avc1.4D401E    97k video only          360p, mp4_dash
18  mp4   480x360     30  2 │ ≈  4.01MiB 222k https │ avc1.42001E        mp4a.40.2       44k 360p
605 mp4   480x360     30    │ ~  4.72MiB 262k m3u8  │ vp09.00.21.08 262k video only
243 webm  480x360     30    │  743.85KiB  40k https │ vp09.00.21.08  40k video only          360p, webm_dash
231 mp4   640x480     30    │ ~ 12.26MiB 681k m3u8  │ avc1.4D401E   681k video only
135 mp4   640x480     30    │    2.65MiB 147k https │ avc1.4D401E   147k video only          480p, mp4_dash
606 mp4   640x480     30    │ ~  5.97MiB 332k m3u8  │ vp09.00.30.08 332k video only
244 webm  640x480     30    │    1.11MiB  62k https │ vp09.00.30.08  62k video only          480p, webm_dash
```

### Expected behavior

Both songs plays just fine.

### Actual behavior

The first song does not play. And after the thrown PlaybackException InnerTune can't recover without pressing next + pause + play manually.

### Logs

```
04-16 16:33:57.455  3014  3014 W System.err: p1.n: Source error
04-16 16:33:57.455  3014  3014 W System.err: 	at p1.T.j(SourceFile:17)
04-16 16:33:57.455  3014  3014 W System.err: 	at p1.T.handleMessage(SourceFile:360)
04-16 16:33:57.455  3014  3014 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-16 16:33:57.455  3014  3014 W System.err: 	at android.os.Looper.loopOnce(Looper.java:205)
04-16 16:33:57.455  3014  3014 W System.err: 	at android.os.Looper.loop(Looper.java:294)
04-16 16:33:57.455  3014  3014 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:67)
04-16 16:33:57.455  3014  3014 W System.err: Caused by: A1.n: Unexpected U: No stream available
04-16 16:33:57.455  3014  3014 W System.err: 	at A1.k.run(SourceFile:136)
04-16 16:33:57.455  3014  3014 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
04-16 16:33:57.455  3014  3014 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
04-16 16:33:57.455  3014  3014 W System.err: 	at java.lang.Thread.run(Thread.java:1012)
04-16 16:33:57.455  3014  3014 W System.err: Caused by: f1.U: No stream available
04-16 16:33:57.455  3014  3014 W System.err: 	at h2.n1.a(SourceFile:583)
04-16 16:33:57.455  3014  3014 W System.err: 	at l1.G.b(SourceFile:3)
04-16 16:33:57.455  3014  3014 W System.err: 	at l1.H.b(SourceFile:10)
04-16 16:33:57.455  3014  3014 W System.err: 	at x1.H.a(SourceFile:26)
04-16 16:33:57.455  3014  3014 W System.err: 	at A1.k.run(SourceFile:37)
04-16 16:33:57.455  3014  3014 W System.err: 	... 3 more
```

### InnerTune version

0.5.6

### Android version

Android 14

**Comment by Malopieds** [comment]
I can actually play both. What does details says?

**Comment by ifacify** [comment]
Unfortunately that's what I got from logcat.  
Actually clearing the app data fixes the problem. I have the problematic app data backed up and will try that on a debug build for a more readable logcat tomorrow.
Also clearing download cache does not fix the problem :)

**Comment by Malopieds** [comment]
It should now play fine, can you check the latest debug build ?

**Comment by Malopieds** [comment]
Closing it since no answer.
