### ISSUE TITLE
Albums don't fetch

### ISSUE THREAD

**Issue by thornySoap** [Malopieds/InnerTune#94]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Click on an album that is not already in the database

### Expected behavior

After a short loading time the songs and information should appear

### Actual behavior

The loading shimmer animation continues forever

### Screenshots/Screen recordings

https://github.com/Malopieds/InnerTune/assets/115401023/6e308a82-fb4f-403c-9400-f0d922b3b55a

### Logs

<details>
<summary><<< log_count = 128 >>></summary>
[05-10 11:10:33.537 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
handleAppVisibility mAppVisible = false visible = true

[05-10 11:10:33.537 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
handleAppVisibility mAppVisible = false visible = true

[05-10 11:10:33.538 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
stopped(false) old = true

[05-10 11:10:33.538 5355:5355 D/ViewRootImpl@cf063e5[MainActivity]]
WindowStopped on com.zionhuang.music/com.zionhuang.music.MainActivity set to false

[05-10 11:10:33.538 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
stopped(false) old = true

[05-10 11:10:33.538 5355:5355 D/ViewRootImpl@cf063e5[MainActivity]]
WindowStopped on com.zionhuang.music/com.zionhuang.music.MainActivity set to false

[05-10 11:10:33.547 5355:5355 W/WindowOnBackDispatcher]
OnBackInvokedCallback is not enabled for the application.
Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.

[05-10 11:10:33.547 5355:5355 W/WindowOnBackDispatcher]
OnBackInvokedCallback is not enabled for the application.
Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.

[05-10 11:10:33.550 5355:5355 D/InsetsController]
onStateChanged: host=com.zionhuang.music/com.zionhuang.music.MainActivity from=android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl:261 state=InsetsState: {mDisplayFrame=Rect(0, 0 - 1080, 2400), mDisplayCutout=DisplayCutout{insets=Rect(0, 0 - 0, 0) waterfall=Insets{left=0, top=0, right=0, bottom=0} boundingRect={Bounds=[Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0)]} cutoutPathParserInfo={CutoutPathParserInfo{displayWidth=1080 displayHeight=2400 physicalDisplayWidth=1080 physicalDisplayHeight=2400 density={3.0} cutoutSpec={M 0,0 L 0, 0 C 0,0 0,0 0,0} rotation={0} scale={1.0} physicalPixelDisplaySizeRatio={1.0}}}}, mRoundedCorners=RoundedCorners{[RoundedCorner{position=TopLeft, radius=112, center=Point(112, 112)}, RoundedCorner{position=TopRight, radius=112, center=Point(968, 112)}, RoundedCorner{position=BottomRight, radius=112, center=Point(968, 2288)}, RoundedCorner{position=BottomLeft, radius=112, center=Point(112, 2288)}]}  mRoundedCornerFrame=Rect(0, 0 - 1080, 2400), mPrivacyIndicatorBounds=PrivacyIndicatorBounds {static bounds=Rect(948, 0 - 1080, 88) rotation=0}, mDisplayShape=DisplayShape{ spec=-1893857183 displayWidth=1080 displayHeight=2400 physicalPixelDisplaySizeRatio=1.0 rotation=0 offsetX=0 offsetY=0 scale=1.0}, mSources= { InsetsSource: {174a0000 mType=statusBars mFrame=[0,0][1080,88] mVisible=true mFlags=[]}, InsetsSource: {174a0005 mType=mandatorySystemGestures mFrame=[0,0][1080,88] mVisible=true mFlags=[]}, InsetsSource: {174a0006 mType=tappableElement mFrame=[0,0][1080,88] mVisible=true mFlags=[]}, InsetsSource: {31230001 mType=navigationBars mFrame=[0,0][0,0] mVisible=true mFlags=[SUPPRESS_SCRIM]}, InsetsSource: {31230004 mType=systemGestures mFrame=[0,0][54,2400] mVisible=true mFlags=[]}, InsetsSource: {31230005 mType=mandatorySystemGestures mFrame=[0,2352][1080,2400] mVisible=true mFlags=[]}, InsetsSource: {31230006 mType=tappableElement mFrame=[0,0][0,0] mVisible=true mFlags=[]}, InsetsSource: {31230024 mType=systemGestures mFrame=[1026,0][1080,2400] mVisible=true mFlags=[]} }

[05-10 11:10:33.550 5355:5355 D/InsetsController]
onStateChanged: host=com.zionhuang.music/com.zionhuang.music.MainActivity from=android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl:261 state=InsetsState: {mDisplayFrame=Rect(0, 0 - 1080, 2400), mDisplayCutout=DisplayCutout{insets=Rect(0, 0 - 0, 0) waterfall=Insets{left=0, top=0, right=0, bottom=0} boundingRect={Bounds=[Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0)]} cutoutPathParserInfo={CutoutPathParserInfo{displayWidth=1080 displayHeight=2400 physicalDisplayWidth=1080 physicalDisplayHeight=2400 density={3.0} cutoutSpec={M 0,0 L 0, 0 C 0,0 0,0 0,0} rotation={0} scale={1.0} physicalPixelDisplaySizeRatio={1.0}}}}, mRoundedCorners=RoundedCorners{[RoundedCorner{position=TopLeft, radius=112, center=Point(112, 112)}, RoundedCorner{position=TopRight, radius=112, center=Point(968, 112)}, RoundedCorner{position=BottomRight, radius=112, center=Point(968, 2288)}, RoundedCorner{position=BottomLeft, radius=112, center=Point(112, 2288)}]}  mRoundedCornerFrame=Rect(0, 0 - 1080, 2400), mPrivacyIndicatorBounds=PrivacyIndicatorBounds {static bounds=Rect(948, 0 - 1080, 88) rotation=0}, mDisplayShape=DisplayShape{ spec=-1893857183 displayWidth=1080 displayHeight=2400 physicalPixelDisplaySizeRatio=1.0 rotation=0 offsetX=0 offsetY=0 scale=1.0}, mSources= { InsetsSource: {174a0000 mType=statusBars mFrame=[0,0][1080,88] mVisible=true mFlags=[]}, InsetsSource: {174a0005 mType=mandatorySystemGestures mFrame=[0,0][1080,88] mVisible=true mFlags=[]}, InsetsSource: {174a0006 mType=tappableElement mFrame=[0,0][1080,88] mVisible=true mFlags=[]}, InsetsSource: {31230001 mType=navigationBars mFrame=[0,0][0,0] mVisible=true mFlags=[SUPPRESS_SCRIM]}, InsetsSource: {31230004 mType=systemGestures mFrame=[0,0][54,2400] mVisible=true mFlags=[]}, InsetsSource: {31230005 mType=mandatorySystemGestures mFrame=[0,2352][1080,2400] mVisible=true mFlags=[]}, InsetsSource: {31230006 mType=tappableElement mFrame=[0,0][0,0] mVisible=true mFlags=[]}, InsetsSource: {31230024 mType=systemGestures mFrame=[1026,0][1080,2400] mVisible=true mFlags=[]} }

[05-10 11:10:33.550 5355:5355 D/InsetsSourceConsumer]
applyRequestedVisibilityToControl: visible=true, type=2

[05-10 11:10:33.550 5355:5355 D/InsetsSourceConsumer]
applyRequestedVisibilityToControl: visible=true, type=2

[05-10 11:10:33.551 5355:5355 D/InsetsSourceConsumer]
applyRequestedVisibilityToControl: visible=true, type=1

[05-10 11:10:33.551 5355:5355 D/InsetsSourceConsumer]
applyRequestedVisibilityToControl: visible=true, type=1

[05-10 11:10:33.562 5355:5355 I/BLASTBufferQueue_Java]
new BLASTBufferQueue, mName= ViewRootImpl@cf063e5[MainActivity] mNativeObject= 0xb4000076e0c43100 sc.mNativeObject= 0xb4000076e0b5d040 caller= android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:67 android.view.ViewRootImpl.relayoutWindow:857 android.view.ViewRootImpl.performTraversals:1336 android.view.ViewRootImpl.doTraversal:42 android.view.ViewRootImpl$TraversalRunnable.run:2 android.view.Choreographer$CallbackRecord.run:20 android.view.Choreographer$CallbackRecord.run:24 android.view.Choreographer.doCallbacks:108 android.view.Choreographer.doFrame:504 android.view.Choreographer$FrameDisplayEventReceiver.run:15 

[05-10 11:10:33.562 5355:5355 I/BLASTBufferQueue_Java]
new BLASTBufferQueue, mName= ViewRootImpl@cf063e5[MainActivity] mNativeObject= 0xb4000076e0c43100 sc.mNativeObject= 0xb4000076e0b5d040 caller= android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:67 android.view.ViewRootImpl.relayoutWindow:857 android.view.ViewRootImpl.performTraversals:1336 android.view.ViewRootImpl.doTraversal:42 android.view.ViewRootImpl$TraversalRunnable.run:2 android.view.Choreographer$CallbackRecord.run:20 android.view.Choreographer$CallbackRecord.run:24 android.view.Choreographer.doCallbacks:108 android.view.Choreographer.doFrame:504 android.view.Choreographer$FrameDisplayEventReceiver.run:15 

[05-10 11:10:33.562 5355:5355 I/BLASTBufferQueue_Java]
update, w= 1080 h= 2400 mName = ViewRootImpl@cf063e5[MainActivity] mNativeObject= 0xb4000076e0c43100 sc.mNativeObject= 0xb4000076e0b5d040 format= -1 caller= android.graphics.BLASTBufferQueue.<init>:117 android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:67 android.view.ViewRootImpl.relayoutWindow:857 android.view.ViewRootImpl.performTraversals:1336 android.view.ViewRootImpl.doTraversal:42 android.view.ViewRootImpl$TraversalRunnable.run:2 

[05-10 11:10:33.562 5355:5355 I/BLASTBufferQueue_Java]
update, w= 1080 h= 2400 mName = ViewRootImpl@cf063e5[MainActivity] mNativeObject= 0xb4000076e0c43100 sc.mNativeObject= 0xb4000076e0b5d040 format= -1 caller= android.graphics.BLASTBufferQueue.<init>:117 android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:67 android.view.ViewRootImpl.relayoutWindow:857 android.view.ViewRootImpl.performTraversals:1336 android.view.ViewRootImpl.doTraversal:42 android.view.ViewRootImpl$TraversalRunnable.run:2 

[05-10 11:10:33.562 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
Relayout returned: old=(0,0,1080,2400) new=(0,0,1080,2400) req=(1080,2400)0 dur=5 res=0x403 s={true 0xb4000076e0c2b800} ch=true seqId=0

[05-10 11:10:33.562 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
Relayout returned: old=(0,0,1080,2400) new=(0,0,1080,2400) req=(1080,2400)0 dur=5 res=0x403 s={true 0xb4000076e0c2b800} ch=true seqId=0

[05-10 11:10:33.563 5355:5355 D/ViewRootImpl@cf063e5[MainActivity]]
mThreadedRenderer.initialize() mSurface={isValid=true 0xb4000076e0c2b800} hwInitialized=true

[05-10 11:10:33.563 5355:5355 D/ViewRootImpl@cf063e5[MainActivity]]
mThreadedRenderer.initialize() mSurface={isValid=true 0xb4000076e0c2b800} hwInitialized=true

[05-10 11:10:33.565 5355:5355 D/ViewRootImpl@cf063e5[MainActivity]]
reportNextDraw android.view.ViewRootImpl.performTraversals:4587 android.view.ViewRootImpl.doTraversal:42 android.view.ViewRootImpl$TraversalRunnable.run:2 android.view.Choreographer$CallbackRecord.run:20 android.view.Choreographer$CallbackRecord.run:24 

[05-10 11:10:33.565 5355:5355 D/ViewRootImpl@cf063e5[MainActivity]]
reportNextDraw android.view.ViewRootImpl.performTraversals:4587 android.view.ViewRootImpl.doTraversal:42 android.view.ViewRootImpl$TraversalRunnable.run:2 android.view.Choreographer$CallbackRecord.run:20 android.view.Choreographer$CallbackRecord.run:24 

[05-10 11:10:33.565 5355:5355 D/ViewRootImpl@cf063e5[MainActivity]]
Setup new sync=wmsSync-ViewRootImpl@cf063e5[MainActivity]#12

[05-10 11:10:33.565 5355:5355 D/ViewRootImpl@cf063e5[MainActivity]]
Setup new sync=wmsSync-ViewRootImpl@cf063e5[MainActivity]#12

[05-10 11:10:33.565 5355:5355 D/ViewRootImpl@cf063e5[MainActivity]]
Creating new active sync group ViewRootImpl@cf063e5[MainActivity]#13

[05-10 11:10:33.565 5355:5355 D/ViewRootImpl@cf063e5[MainActivity]]
Creating new active sync group ViewRootImpl@cf063e5[MainActivity]#13

[05-10 11:10:33.565 5355:5355 D/ViewRootImpl@cf063e5[MainActivity]]
registerCallbacksForSync syncBuffer=false

[05-10 11:10:33.565 5355:5355 D/ViewRootImpl@cf063e5[MainActivity]]
registerCallbacksForSync syncBuffer=false

[05-10 11:10:33.585 5355:5401 D/ViewRootImpl@cf063e5[MainActivity]]
Received frameDrawingCallback syncResult=0 frameNum=1.

[05-10 11:10:33.585 5355:5401 D/ViewRootImpl@cf063e5[MainActivity]]
Received frameDrawingCallback syncResult=0 frameNum=1.

[05-10 11:10:33.585 5355:5401 I/ViewRootImpl@cf063e5[MainActivity]]
mWNT: t=0xb40000767da39680 mBlastBufferQueue=0xb4000076e0c43100 fn= 1 caller= android.view.ViewRootImpl$8.onFrameDraw:58 android.view.ThreadedRenderer$1.onFrameDraw:22 <bottom of call stack> 

[05-10 11:10:33.585 5355:5401 D/ViewRootImpl@cf063e5[MainActivity]]
Setting up sync and frameCommitCallback

[05-10 11:10:33.585 5355:5401 I/ViewRootImpl@cf063e5[MainActivity]]
mWNT: t=0xb40000767da39680 mBlastBufferQueue=0xb4000076e0c43100 fn= 1 caller= android.view.ViewRootImpl$8.onFrameDraw:58 android.view.ThreadedRenderer$1.onFrameDraw:22 <bottom of call stack> 

[05-10 11:10:33.585 5355:5401 D/ViewRootImpl@cf063e5[MainActivity]]
Setting up sync and frameCommitCallback

[05-10 11:10:33.590 5355:5379 I/BLASTBufferQueue]
[ViewRootImpl@cf063e5[MainActivity]#6](f:0,a:0,s:0) onFrameAvailable the first frame is available

[05-10 11:10:33.590 5355:5379 I/BLASTBufferQueue]
[ViewRootImpl@cf063e5[MainActivity]#6](f:0,a:0,s:0) onFrameAvailable the first frame is available

[05-10 11:10:33.591 5355:5379 D/ViewRootImpl@cf063e5[MainActivity]]
Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true

[05-10 11:10:33.591 5355:5379 D/ViewRootImpl@cf063e5[MainActivity]]
Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true

[05-10 11:10:33.591 5355:5355 D/ViewRootImpl@cf063e5[MainActivity]]
reportDrawFinished

[05-10 11:10:33.591 5355:5355 D/ViewRootImpl@cf063e5[MainActivity]]
reportDrawFinished

[05-10 11:10:33.619 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
registerCallbackForPendingTransactions

[05-10 11:10:33.619 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
registerCallbackForPendingTransactions

[05-10 11:10:33.637 5355:5400 I/ViewRootImpl@cf063e5[MainActivity]]
mWNT: t=0xb40000766ff51f00 mBlastBufferQueue=0xb4000076e0c43100 fn= 2 caller= android.view.ViewRootImpl$6.onFrameDraw:4 android.view.ViewRootImpl$2.onFrameDraw:2 android.view.ThreadedRenderer$1.onFrameDraw:22 

[05-10 11:10:33.637 5355:5400 I/ViewRootImpl@cf063e5[MainActivity]]
mWNT: t=0xb40000766ff51f00 mBlastBufferQueue=0xb4000076e0c43100 fn= 2 caller= android.view.ViewRootImpl$6.onFrameDraw:4 android.view.ViewRootImpl$2.onFrameDraw:2 android.view.ThreadedRenderer$1.onFrameDraw:22 

[05-10 11:10:33.646 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
MSG_WINDOW_FOCUS_CHANGED 1 0

[05-10 11:10:33.646 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
MSG_WINDOW_FOCUS_CHANGED 1 0

[05-10 11:10:33.646 5355:5355 D/ViewRootImpl@cf063e5[MainActivity]]
mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb4000076e0c2b800}

[05-10 11:10:33.646 5355:5355 D/InputMethodManagerUtils]
startInputInner - Id : 0

[05-10 11:10:33.646 5355:5355 D/ViewRootImpl@cf063e5[MainActivity]]
mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb4000076e0c2b800}

[05-10 11:10:33.646 5355:5355 D/InputMethodManagerUtils]
startInputInner - Id : 0

[05-10 11:10:33.647 5355:5355 I/InputMethodManager]
startInputInner - IInputMethodManagerGlobalInvoker.startInputOrWindowGainedFocus

[05-10 11:10:33.647 5355:5355 I/InputMethodManager]
startInputInner - IInputMethodManagerGlobalInvoker.startInputOrWindowGainedFocus

[05-10 11:10:33.657 5355:5355 D/InsetsController]
onStateChanged: host=com.zionhuang.music/com.zionhuang.music.MainActivity from=android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl:261 state=InsetsState: {mDisplayFrame=Rect(0, 0 - 1080, 2400), mDisplayCutout=DisplayCutout{insets=Rect(0, 0 - 0, 0) waterfall=Insets{left=0, top=0, right=0, bottom=0} boundingRect={Bounds=[Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0)]} cutoutPathParserInfo={CutoutPathParserInfo{displayWidth=1080 displayHeight=2400 physicalDisplayWidth=1080 physicalDisplayHeight=2400 density={3.0} cutoutSpec={M 0,0 L 0, 0 C 0,0 0,0 0,0} rotation={0} scale={1.0} physicalPixelDisplaySizeRatio={1.0}}}}, mRoundedCorners=RoundedCorners{[RoundedCorner{position=TopLeft, radius=112, center=Point(112, 112)}, RoundedCorner{position=TopRight, radius=112, center=Point(968, 112)}, RoundedCorner{position=BottomRight, radius=112, center=Point(968, 2288)}, RoundedCorner{position=BottomLeft, radius=112, center=Point(112, 2288)}]}  mRoundedCornerFrame=Rect(0, 0 - 1080, 2400), mPrivacyIndicatorBounds=PrivacyIndicatorBounds {static bounds=Rect(948, 0 - 1080, 88) rotation=0}, mDisplayShape=DisplayShape{ spec=-1893857183 displayWidth=1080 displayHeight=2400 physicalPixelDisplaySizeRatio=1.0 rotation=0 offsetX=0 offsetY=0 scale=1.0}, mSources= { InsetsSource: {3 mType=ime mFrame=[0,0][0,0] mVisible=false mFlags=[]}, InsetsSource: {174a0000 mType=statusBars mFrame=[0,0][1080,88] mVisible=true mFlags=[]}, InsetsSource: {174a0005 mType=mandatorySystemGestures mFrame=[0,0][1080,88] mVisible=true mFlags=[]}, InsetsSource: {174a0006 mType=tappableElement mFrame=[0,0][1080,88] mVisible=true mFlags=[]}, InsetsSource: {31230001 mType=navigationBars mFrame=[0,0][0,0] mVisible=true mFlags=[SUPPRESS_SCRIM]}, InsetsSource: {31230004 mType=systemGestures mFrame=[0,0][54,2400] mVisible=true mFlags=[]}, InsetsSource: {31230005 mType=mandatorySystemGestures mFrame=[0,2352][1080,2400] mVisible=true mFlags=[]}, InsetsSource: {31230006 mType=tappableElement mFrame=[0,0][0,0] mVisible=true mFlags=[]}, InsetsSource: {31230024 mType=systemGestures mFrame=[1026,0][1080,2400] mVisible=true mFlags=[]} }

[05-10 11:10:33.657 5355:5355 D/InsetsController]
onStateChanged: host=com.zionhuang.music/com.zionhuang.music.MainActivity from=android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl:261 state=InsetsState: {mDisplayFrame=Rect(0, 0 - 1080, 2400), mDisplayCutout=DisplayCutout{insets=Rect(0, 0 - 0, 0) waterfall=Insets{left=0, top=0, right=0, bottom=0} boundingRect={Bounds=[Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0)]} cutoutPathParserInfo={CutoutPathParserInfo{displayWidth=1080 displayHeight=2400 physicalDisplayWidth=1080 physicalDisplayHeight=2400 density={3.0} cutoutSpec={M 0,0 L 0, 0 C 0,0 0,0 0,0} rotation={0} scale={1.0} physicalPixelDisplaySizeRatio={1.0}}}}, mRoundedCorners=RoundedCorners{[RoundedCorner{position=TopLeft, radius=112, center=Point(112, 112)}, RoundedCorner{position=TopRight, radius=112, center=Point(968, 112)}, RoundedCorner{position=BottomRight, radius=112, center=Point(968, 2288)}, RoundedCorner{position=BottomLeft, radius=112, center=Point(112, 2288)}]}  mRoundedCornerFrame=Rect(0, 0 - 1080, 2400), mPrivacyIndicatorBounds=PrivacyIndicatorBounds {static bounds=Rect(948, 0 - 1080, 88) rotation=0}, mDisplayShape=DisplayShape{ spec=-1893857183 displayWidth=1080 displayHeight=2400 physicalPixelDisplaySizeRatio=1.0 rotation=0 offsetX=0 offsetY=0 scale=1.0}, mSources= { InsetsSource: {3 mType=ime mFrame=[0,0][0,0] mVisible=false mFlags=[]}, InsetsSource: {174a0000 mType=statusBars mFrame=[0,0][1080,88] mVisible=true mFlags=[]}, InsetsSource: {174a0005 mType=mandatorySystemGestures mFrame=[0,0][1080,88] mVisible=true mFlags=[]}, InsetsSource: {174a0006 mType=tappableElement mFrame=[0,0][1080,88] mVisible=true mFlags=[]}, InsetsSource: {31230001 mType=navigationBars mFrame=[0,0][0,0] mVisible=true mFlags=[SUPPRESS_SCRIM]}, InsetsSource: {31230004 mType=systemGestures mFrame=[0,0][54,2400] mVisible=true mFlags=[]}, InsetsSource: {31230005 mType=mandatorySystemGestures mFrame=[0,2352][1080,2400] mVisible=true mFlags=[]}, InsetsSource: {31230006 mType=tappableElement mFrame=[0,0][0,0] mVisible=true mFlags=[]}, InsetsSource: {31230024 mType=systemGestures mFrame=[1026,0][1080,2400] mVisible=true mFlags=[]} }

[05-10 11:10:33.657 5355:5372 I/ViewRootImpl@cf063e5[MainActivity]]
Resizing android.view.ViewRootImpl@a27fea0: frame = [0,0][1080,2400] reportDraw = false forceLayout = false syncSeqId = -1

[05-10 11:10:33.657 5355:5355 D/InsetsSourceConsumer]
applyRequestedVisibilityToControl: visible=false, type=8

[05-10 11:10:33.657 5355:5372 I/ViewRootImpl@cf063e5[MainActivity]]
Resizing android.view.ViewRootImpl@a27fea0: frame = [0,0][1080,2400] reportDraw = false forceLayout = false syncSeqId = -1

[05-10 11:10:33.657 5355:5355 D/InsetsSourceConsumer]
applyRequestedVisibilityToControl: visible=false, type=8

[05-10 11:10:33.658 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
handleResized, msg = 4 frames=ClientWindowFrames{frame=[0,0][1080,2400] display=[0,0][1080,2400] parentFrame=[0,0][0,0]} forceNextWindowRelayout=false displayId=0 dragResizing=false compatScale=1.0 frameChanged=false attachedFrameChanged=false configChanged=false displayChanged=false compatScaleChanged=false

[05-10 11:10:33.658 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
handleResized, msg = 4 frames=ClientWindowFrames{frame=[0,0][1080,2400] display=[0,0][1080,2400] parentFrame=[0,0][0,0]} forceNextWindowRelayout=false displayId=0 dragResizing=false compatScale=1.0 frameChanged=false attachedFrameChanged=false configChanged=false displayChanged=false compatScaleChanged=false

[05-10 11:10:34.914 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
ViewPostIme pointer 0

[05-10 11:10:34.914 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
ViewPostIme pointer 0

[05-10 11:10:34.960 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
ViewPostIme pointer 1

[05-10 11:10:34.960 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
ViewPostIme pointer 1

[05-10 11:10:35.127 5355:15233 D/TrafficStats]
tagSocket(140) with statsTag=0xffffffff, statsUid=-1

[05-10 11:10:35.127 5355:15233 D/TrafficStats]
tagSocket(140) with statsTag=0xffffffff, statsUid=-1

[05-10 11:10:35.369 5355:5355 W/System.err]
java.lang.NullPointerException

[05-10 11:10:35.369 5355:5355 W/System.err]
java.lang.NullPointerException

[05-10 11:10:35.369 5355:5355 W/System.err]
	at b3.G.b(SourceFile:253)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at b3.f.l(SourceFile:14)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at J4.a.A(SourceFile:9)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at a5.I.run(SourceFile:95)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at a5.U.z0(SourceFile:24)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at g5.i.A(SourceFile:75)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at u4.k.g(SourceFile:25)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at u4.k.f(SourceFile:16)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at u4.j.A(SourceFile:23)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at J4.a.A(SourceFile:32)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at a5.I.run(SourceFile:95)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at android.os.Handler.handleCallback(Unknown Source:2)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at android.os.Handler.dispatchMessage(Unknown Source:4)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at android.os.Looper.loopOnce(Unknown Source:185)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at android.os.Looper.loop(Unknown Source:83)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at android.app.ActivityThread.main(Unknown Source:107)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at java.lang.reflect.Method.invoke(Native Method)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at com.android.internal.os.ZygoteInit.main(Unknown Source:334)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at b3.G.b(SourceFile:253)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at b3.f.l(SourceFile:14)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at J4.a.A(SourceFile:9)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at a5.I.run(SourceFile:95)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at a5.U.z0(SourceFile:24)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at g5.i.A(SourceFile:75)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at u4.k.g(SourceFile:25)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at u4.k.f(SourceFile:16)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at u4.j.A(SourceFile:23)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at J4.a.A(SourceFile:32)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at a5.I.run(SourceFile:95)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at android.os.Handler.handleCallback(Unknown Source:2)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at android.os.Handler.dispatchMessage(Unknown Source:4)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at android.os.Looper.loopOnce(Unknown Source:185)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at android.os.Looper.loop(Unknown Source:83)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at android.app.ActivityThread.main(Unknown Source:107)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at java.lang.reflect.Method.invoke(Native Method)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)

[05-10 11:10:35.369 5355:5355 W/System.err]
	at com.android.internal.os.ZygoteInit.main(Unknown Source:334)

[05-10 11:10:44.749 5355:5355 W/Choreographer]
Frame time is 0.009484 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.

[05-10 11:10:44.749 5355:5355 W/Choreographer]
Frame time is 0.009484 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.

[05-10 11:10:55.673 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
ViewPostIme pointer 0

[05-10 11:10:55.673 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
ViewPostIme pointer 0

[05-10 11:10:55.817 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
MSG_WINDOW_FOCUS_CHANGED 0 0

[05-10 11:10:55.817 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
MSG_WINDOW_FOCUS_CHANGED 0 0

[05-10 11:10:57.731 5355:5355 D/InsetsSourceConsumer]
applyRequestedVisibilityToControl: visible=true, type=2

[05-10 11:10:57.731 5355:5355 D/InsetsSourceConsumer]
applyRequestedVisibilityToControl: visible=true, type=2

[05-10 11:10:57.734 5355:5355 D/InsetsSourceConsumer]
applyRequestedVisibilityToControl: visible=true, type=1

[05-10 11:10:57.734 5355:5355 D/InsetsSourceConsumer]
applyRequestedVisibilityToControl: visible=true, type=1

[05-10 11:10:57.805 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
handleAppVisibility mAppVisible = true visible = false

[05-10 11:10:57.805 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
handleAppVisibility mAppVisible = true visible = false

[05-10 11:10:57.823 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
Relayout returned: old=(0,0,1080,2400) new=(0,0,1080,2400) req=(1080,2400)8 dur=8 res=0x402 s={false 0x0} ch=true seqId=0

[05-10 11:10:57.823 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
Relayout returned: old=(0,0,1080,2400) new=(0,0,1080,2400) req=(1080,2400)8 dur=8 res=0x402 s={false 0x0} ch=true seqId=0

[05-10 11:10:57.840 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
stopped(true) old = false

[05-10 11:10:57.840 5355:5355 D/ViewRootImpl@cf063e5[MainActivity]]
WindowStopped on com.zionhuang.music/com.zionhuang.music.MainActivity set to true

[05-10 11:10:57.840 5355:5355 I/ViewRootImpl@cf063e5[MainActivity]]
stopped(true) old = false

[05-10 11:10:57.840 5355:5355 D/ViewRootImpl@cf063e5[MainActivity]]
WindowStopped on com.zionhuang.music/com.zionhuang.music.MainActivity set to true

[05-10 11:10:57.901 5355:5355 D/InputTransport]
Input channel destroyed: 'ClientS', fd=139

[05-10 11:10:57.901 5355:5355 D/InputTransport]
Input channel destroyed: 'ClientS', fd=139

</details>

### InnerTune version

0.5.7-rc1

### Android version

14 OneUI 6.0

**Comment by thornySoap** [comment]
It works again now. Doesn't seem to be a problem in the app, but something with Youtube.

**Comment by Sofa44** [comment]
What was the problem with youtube? I'm having this same issue and can't seem to fix it.
